#!/usr/bin/env bash
# checking for command line arguments34 
# By: Natnale Bimer

if [S#-1t 4 ]
then
	echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to variables

path_to_file=$1
ip=$2
username=$3
path_to_shh_key=$4

# disabbling strict host key checking

scp -o "StrictHostKeychecking=no" -i "Spath_to_ssh_key" "Spath_to_file" "Susername@Sip:-/"

# checking if the transfer was successful
if [ $? -eq 0 ]
then
	echo "Transfer successful"
else
	echo "Transfer Failed"
fi
